### ISSUE TITLE
fix(install): create a .tmp/ directory

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#1]
Required by `bin/extract-unicode-pinyin.bash` otherwise get the following error:

```
bin/extract-unicode-pinyin.bash: line 58: /home/elopez/projects/Hanzi-Pinyin-Font/.tmp/unicode-pinyin.csv: No such file or directory
```

**Comment by DaWy** [comment]
I'm having this issue when trying to compile. The directory is there, but no unicode-pinyin.csv. Any hint on this? Also there is no bin/extract-unicode-pinyin.bash.

> /bin/bash: bin/extract-unicode-pinyin.bash: No existe el archivo o el directorio
makefile:82: fallo en las instrucciones para el objetivo '.tmp/unicode-pinyin.csv'
make: *** [.tmp/unicode-pinyin.csv] Error 127

**Comment by hugolpz** [comment]
I recommend you to switch to English and google the error, it may provide more results.

**Comment by edouard-lopez** [comment]
Thanks @DaWy, I'm droping the bash/PHP approach to go for a javascript/TDD solution.

I close this issue as not relevant anymore.
