### ISSUE TITLE
Print out to SVG file

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#10]

**Comment by edouard-lopez** [comment]
see a2a2fb07ef.

**Comment by hugolpz** [comment]
Solved.
![screenshot from 2017-02-22 23-59-43](https://cloud.githubusercontent.com/assets/1420189/23236923/71f3018e-f95b-11e6-98bc-e56f6454d7b6.png)

Check out branch hugo : https://github.com/edouard-lopez/Hanzi-Pinyin-Font/tree/hugo

**Comment by hugolpz** [comment]
@edouard-lopez : please checkout and merge if ok !

**Comment by edouard-lopez** [comment]
close by [86c4a1fa414dc7ede4140f0841ad2a3ad776e18c](86c4a1fa414dc7ede4140f0841ad2a3ad776e18c/index.js#L22)
