### ISSUE TITLE
process more than one glyph

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#13]

**Comment by hugolpz** [comment]
Done ! [Branch "hugo" > This commit](https://github.com/edouard-lopez/Hanzi-Pinyin-Font/commit/37835988064436ae8b73835acab827f914309753#diff-168726dbe96b3ce427e7fedce31bb0bc)
![screenshot from 2017-02-23 12-23-50](https://cloud.githubusercontent.com/assets/1420189/23257222/3201c840-f9c3-11e6-8511-b0521a8ea14f.png)
