### ISSUE TITLE
Enhance the readme.md via png illustrations. 

### ISSUE THREAD

**Issue by hugolpz** [parlr/ruby-font-creator#16]
For md image inclusion syntaxe, review [PeergraderJS > readme.md](https://github.com/CyberCRI/PeerGradersJS/blob/master/README.md)

**Comment by hugolpz** [comment]
[Done](https://github.com/edouard-lopez/Hanzi-Pinyin-Font/commit/bb05c9eb079041b99ebdd0734f4aade1e2c3980d#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by edouard-lopez** [comment]
Thanks for the works.
