### ISSUE TITLE
Data gathering

### ISSUE THREAD

**Issue by hugolpz** [parlr/ruby-font-creator#19]
We currently look for database with` { "glyph": "西", "phonetic": "xī" }` (or `xi1`, or alternatives).

Sources possible, info to complete :

### Moedict 
- [ ] link (to complete)
- [ ] json format
- [ ] range : most common caracters, trad only ?
### Unicode :
- [ ] link (to complete)
- [x] xml
- [x] range : traditional/modern ; -more complete for a font
- [ ] which phonetic format its provided also. ("glyph": "西", "phonetic": "xī" or xi1 ?)

### CJKlib
- [x] [link](https://cjklib.readthedocs.io/en/latest/installing.html#database)

**Comment by edouard-lopez** [comment]
What about [Unihan](http://www.unicode.org/Public/5.0.0/ucd/Unihan.html)?

With the [hexadecimal codepoint we can get the glyph](http://stackoverflow.com/a/42840113/802365) like this in Python:

    >>> print(chr(int('0x897F', 16)))
    西

A JS solution would be better, but this  is out of the scope of the project, we can do it anyway we think fits.

**Comment by hugolpz** [comment]
Please check out : 
- [unihan results](https://www.npmjs.com/browse/keyword/unihan)
-- npm [unihan](https://github.com/tobei/unihan/blob/master/index.js)
-- npm [convertPinyin](https://www.npmjs.com/package/convertPinyin)
-- npm [unihan-cjk](https://www.npmjs.com/package/cjk-unihan)

![screenshot from 2017-03-16 17-59-36](https://cloud.githubusercontent.com/assets/1420189/24011148/3a909c8a-0a7a-11e7-88ad-2e4ccab8c311.png)
![screenshot from 2017-03-16 17-58-24](https://cloud.githubusercontent.com/assets/1420189/24011149/3aa204d4-0a7a-11e7-8736-19ce4a9e989e.png)


- PinNum2PinTones
-- npm [pinyinize](https://www.npmjs.com/package/pinyinize)
-- [pinyin-string](https://www.npmjs.com/package/pinyin-string) -- best one !

**Comment by edouard-lopez** [comment]
Thanks for the link [cjk-unihan](https://github.com/texh/cjk-unihan) might be useful for other projects.

I think it's better to limit the project to generating font and outsource the data gathering/validation to another project. This way we stay focus and efficient.

I'm closing as different users might have different needs hence handcraft their dictionaries.

**Comment by edouard-lopez** [comment]
I reckon the JS solution is in [tobei/unihan](https://github.com/tobei/unihan/blob/4c6de8109e4abcfb568f34f121d1bb7f9475191e/index.js#L58) code

    const character = String.fromCodePoint(parseInt(code.substring(2), 16));

**Comment by hugolpz** [comment]
Did you gathered the data ?

**Comment by edouard-lopez** [comment]
Not yet, could you work on a project to do so?

**Comment by hugolpz** [comment]
Yup. See also https://github.com/peterolson/pinyinify/issues/1#issuecomment-287167463

![screenshot from 2017-03-17 11-16-25](https://cloud.githubusercontent.com/assets/1420189/24038779/3864da64-0b03-11e7-89a9-6d2cbe73cd9e.png)

**Comment by edouard-lopez** [comment]
@hugolpz I think you have a typo in your comment, there is a ratio of 1:10 between node-pinyin and unihan characters/phonetic pairs. Can you confirm/correct this number?

**Comment by hugolpz** [comment]
https://github.com/superbiger/pinyin4js/blob/master/src/dict/pinyin.dict.js

**Comment by edouard-lopez** [comment]
We can get the codepoint using [`punycode`](https://www.npmjs.com/package/punycode)
