### ISSUE TITLE
Base font consideration

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#2]
Which font should I used for this project?
- [ ] It need to be open-source in order to allow reusability ;
- [ ] lighter font will help on mobile device ;
- [ ] support for ASCII-latin characters ;
- [ ] support italic/bold ;

Here are some possibilities (from the top of my head):
* [x] [DroidSansFallbackFull](https://github.com/parlr/platform_frameworks_base/blob/master/data/fonts/) ;
* [ ] [DéjàVu Sans ](https://github.com/dejavu-fonts/dejavu-fonts) fonts family ;
* [ ] ~~[Droid](https://www.wikiwand.com/en/Droid_fonts) fonts family~~ (see How does [Noto relate to Droid?](https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md#how-does-noto-relate-to-droid))
* [ ] ~~[Noto Sans](https://github.com/googlei18n/noto-fonts)~~, ~~[Noto CJK](https://github.com/googlei18n/noto-cjk)~~ (see googlei18n/noto-cjk#81) ;
* [ ] [Ubuntu](http://font.ubuntu.com/) fonts family.

**Comment by edouard-lopez** [comment]
One [comment by hrzhu](http://chinese.stackexchange.com/questions/3668/are-there-any-free-fonts-designed-to-help-learn-read-chinese#comment14925_3668) on [Are there any free fonts designed to help learn/read Chinese?](http://chinese.stackexchange.com/q/3668/3207) suggest:
- [Wen Quan Yi fonts family](http://wenq.org/wqy2/index.cgi)

**Comment by baimafeima** [comment]
You might want to take a look at this curated list of Chinese fonts: https://github.com/kevchentw/awesome-chinese-fonts

**Comment by edouard-lopez** [comment]
One of the idea of the project is to be able to switch the base font easily to generate different variant.

**Comment by edouard-lopez** [comment]
@hugolpz suggested `Kaishu` and `Mingti` in #14:

> https://github.com/saiswa/free-fonts

**Comment by hugolpz** [comment]
Note : I added a font for the phonetics.
Still need a set of free Chinese fonts for the orthography.

**Comment by edouard-lopez** [comment]
_Noto Sans_ [isn't working as expected](googlei18n/noto-cjk#81) I'm using an old version of _[DroidSansFallbackFull](https://github.com/parlr/platform_frameworks_base/blob/master/data/fonts/)_.

**Comment by edouard-lopez** [comment]
I'm closing for now as I have a **[working version of DroidSansFallbackFull](https://github.com/parlr/platform_frameworks_base/blob/562c45cc841681ed80d4e94515b23c28eb60eae4/data/fonts/DroidSansFallbackFull.ttf)**.
