### ISSUE TITLE
Reorganize projects roles, naming, repositories

### ISSUE THREAD

**Issue by hugolpz** [parlr/ruby-font-creator#20]
- `parlr/ruby-font-maker` : Stand alone NodeJS module.
  - input : 2 fonts, a table of glyph / annotation pairs
  - output : 1 font.
- `parlr/Hanzi-Pinyin-Data` : `data = [ { glyph: "", annotation: [ "", "", ... ] }, {...} ]:`
- `parlr/Hanzi-Pinyin-Font` :
  - input : 1 CJK font + 1 latin font, Hanzi-Pinyin-Data
  - runs `ruby-font-maker` on them !
  - output : ./Hanzi-Pinyin-Font.otf (font)

I thus suggest to rename the current repository + stack of issues `ruby-font-maker`. A bit problematic as of our 10 gh-followers !

**Comment by edouard-lopez** [comment]
For the project name, I will go for: 

* `parlr/ruby-font-creator`
* `parlr/chinese-data`
* `parlr/chinese-ruby-font`

We could mention the followers, to let them know about the change, when we have the 1st release.

**Comment by edouard-lopez** [comment]
* [`parlr/ruby-font-creator`](https://github.com/parlr/ruby-font-creator/) ;
* [`parlr/chinese-data`](https://github.com/parlr/chinese-data) ;
* Instead of ~`parlr/chinese-ruby-font`~, I use the name [`parlr/hanzi-pinyin-font`](https://github.com/parlr/hanzi-pinyin-font) (more explicit).
