### ISSUE TITLE
Associate glyph with correct codepoint

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#22]
The [font generation](#12) works but the glyph are on a private plan. For instance `中` is associate with `U+EA02 <Private Use>` instead of `U+4E2D CJK UNIFIED IDEOGRAPH-4E2D`:

> **General Character Properties**
> In Unicode since: 1.1
> Unicode category: Other, Private Use
> 
> **Various Useful Representations**
> UTF-8: 0xEE 0xA8 0x82
> UTF-16: 0xEA02
> 
> C octal escaped UTF-8: \356\250\202
> XML decimal entity: &#59906;

We need to investigate [webfont](https://github.com/itgalaxy/webfont) in depth.

**related:** itgalaxy/webfont#53 How can I choose the codepoint of a glyph.

**Comment by edouard-lopez** [comment]
done by a38f4af1bc74d14291d8735aa8faebdc49c278f0.

**Comment by hugolpz** [comment]
How. How ?!

**Comment by edouard-lopez** [comment]
see [itgalaxy/webfont#53](https://github.com/itgalaxy/webfont/issues/53#issuecomment-291314425) or [`svgicons2svgfont` CLI section](https://github.com/nfroidure/svgicons2svgfont#cli-interface).

**Comment by hugolpz** [comment]
T'as changé de font maker :)
