### ISSUE TITLE
Renaming repo → update remote URL

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#27]
I rename the project from _Hanzi-Pinyin-Font_ to _ruby-font-creator_, you need to update your remote URL:

    git remote set-url  origin git@github.com:parlr/ruby-font-creator.git

**Comment by edouard-lopez** [comment]
@hugolpz did you update your remote url? I will close this issue at the end of the week-end.

**Comment by hugolpz** [comment]
yes.
@edouard-lopez : If a task is for me alone, please use @hugolpz to call me to action.

**Comment by edouard-lopez** [comment]
It was assigned to you, you should have received notification.
