### ISSUE TITLE
Read about chinese font fundamental

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#42]
[Fundamentals of Chinese Typography: #1 Fonts Styles (Songti, Fangsongti, Mingti, Heiti, Kaiti)
](https://jiromaiya.wordpress.com/2013/01/04/fundamentals-of-chinese-typography-1-fonts-styles-typefaces-songti-fangsongti-mingti-heiti-kaiti/)

**Comment by edouard-lopez** [comment]
@hugolpz must read article

For educational purpose we should try to use _song ti_ or _kai ti_ style

| Kai-ti | Song-ti
| --- | --- |
![kai-ti](https://user-images.githubusercontent.com/1212392/37242826-f612abb4-246f-11e8-8c9d-3d83aaf770c2.jpg) | ![song-ti](https://user-images.githubusercontent.com/1212392/37242857-5ba9acde-2470-11e8-80ec-5925134b8281.jpg)


There is an interesting naming convention for chinese typeface:

> A Chinese typefac
e name is made up of the font name + font style + typeface style (if any) + language specification.

![chinese typeface naming convention 02](https://user-images.githubusercontent.com/1212392/37242882-b2b8ec4c-2470-11e8-9ed2-4871d0618b25.jpg)


![chinese typeface naming convention example](https://user-images.githubusercontent.com/1212392/37242849-476634b8-2470-11e8-9fdb-2a132deaad03.png)

**Comment by hugolpz** [comment]
Source added to Commons project.
