### ISSUE TITLE
 Convert text to SVG path -- solved but to integrate

### ISSUE THREAD

**Issue by edouard-lopez** [parlr/ruby-font-creator#5]
- JS [text-to-svg](https://github.com/shrhdk/text-to-svg): Convert text to SVG path without native dependence using ;
- using [Inkscape v0.49+ `--export-text-to-path` option](http://stackoverflow.com/a/7742345/802365) ;

**Comment by edouard-lopez** [comment]
`text-to-svg` seems a straight-forward solution to position and add rotation:

```
const TextToSVG = require('text-to-svg');
const textToSVG = TextToSVG.loadSync();

const attributes = {fill: 'red', stroke: 'black'};
const options = {x: 0, y: 0, fontSize: 72, anchor: 'top', attributes: attributes};

const svg = textToSVG.getSVG('hello', options);

console.log(svg);
```

**Comment by hugolpz** [comment]
See 
- https://www.npmjs.com/package/text-to-svg
 - dependence : https://www.npmjs.com/package/opentype.js
![screenshot from 2016-12-08 15-24-30](https://cloud.githubusercontent.com/assets/1420189/21013452/6fc93fd2-bd5a-11e6-9796-641b7230609b.png)
![screenshot from 2016-12-08 15-23-58](https://cloud.githubusercontent.com/assets/1420189/21013453/6fcae2b0-bd5a-11e6-92ee-17fc5dd01be0.png)

It works quite quickly, basic js and svg : 
![screenshot from 2016-12-08 16-07-45](https://cloud.githubusercontent.com/assets/1420189/21015216/6b08e6c6-bd61-11e6-8b1f-b7843043ad5d.png)


- Pastebin for code : https://jsfiddle.net/dhuh6h6o/2/ 
- Run it online : https://runkit.com/npm/text-to-svg

I used absolute positioning and `text-anchor` but `translation()` could be nice as well. 
We could do vertical text as well.

Key methods of the module are the following :
```
const textToSVG = TextToSVG.loadSync();                                  // load default font
const textToSVG = TextToSVG.loadSync('/fonts/Noto-Sans.otf'); // local custom font

.getD(text, options = {}) : Get the path data for d attribute of path.
.getPath(text, options = {}) : Get the path element of SVG.
.getSVG(text, options = {}) : Get the SVG.
```

**Comment by edouard-lopez** [comment]
I pushed some tests I had written.

**Comment by hugolpz** [comment]
Please add a ./fonts/ directory and your base open font to the repository.
I would like to give it a try this weekend, at least to output nice svg with balanced, etlegant sinograms and phonetic.

**Comment by hugolpz** [comment]
Solved.
Check out branch `hugo` : https://github.com/edouard-lopez/Hanzi-Pinyin-Font/tree/hugo

**Comment by edouard-lopez** [comment]
Thanks I improved the method [`annotation()`](https://github.com/edouard-lopez/Hanzi-Pinyin-Font/blob/59d1d3f5d507644a03e20ed60f6e96c6032531a9/src/ruby.js) to [use <path>](d9caa0483f6df010872656d28b4384ee69c12aa2) like you
