### ISSUE TITLE
Fix(install) for php5 on classic ubuntu distribs

### ISSUE THREAD

**Issue by hugolpz** [parlr/ruby-font-creator#7]
`git clone`, `npm install` roll out smoothly.

`make install-requirements` fails due to php5 : 

![screenshot from 2016-12-06 00-10-09](https://cloud.githubusercontent.com/assets/1420189/20906543/e3bda6e4-bb48-11e6-8da5-03c94eebe246.png)

You may gain to improve your make file. There is a lead : http://askubuntu.com/questions/756879/cant-install-php5-on-ubuntu-16-04

**Comment by edouard-lopez** [comment]
Thanks for the feedback, a quick fix is to install `php7` instead of `php5`:

```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.0  # php-gettext php-xdebug libapache2-mod-php7.0
```

But I would like to get away from using PHP altogether to focus on JS.

**Comment by hugolpz** [comment]
Talk on npm module for SVG conversion moved to [/issues/5](https://github.com/edouard-lopez/Hanzi-Pinyin-Font/issues/5).

**Comment by edouard-lopez** [comment]
Thanks, might be useful to know about `opentype.js`. I did some test with `text-to-svg` it's working and will serve as a base component for the project.

**Comment by edouard-lopez** [comment]
I will use [`webfont`](https://www.npmjs.com/package/webfont) package in the future so PHP should not be necessary anymore.
